#
# Example docker-compose.yml file for Alike. 
#
version: "3.7"
volumes:
    cache-dbs:
    instaboot:

services:
    alike:
        container_name: alike
        image: quadricsoftware/alike-v7:9631b
        stop_grace_period: 60s
        privileged: true
        init: true
        restart: always
        entrypoint: /a3init
        ports:
            - "80:80"
            - "443:443"
            - "445:445"
            - "2811:2811"
            - "222:22"
            - "2049:2049"
            - "111:111"
        tty: true
        volumes:
            - "/mnt/ads:/mnt/ads"
            - "/mnt/ods:/mnt/ods1"
            - "./logs:/home/alike/logs"
            - "./certs:/home/alike/certs"
            - "./configs:/home/alike/configs"
            - "cache-dbs:/home/alike/Alike/remoteDBs"
            - "instaboot:/mnt/instaboot"
        tmpfs:
            - /home/alike/Alike/temp:uid=1000,gid=33
            - /home/alike/Alike/DBs:uid=1000,gid=1000,exec
            - /run:uid=1000,gid=33
        networks:
            - alike-net
        environment:
            HOST_BLD: ${HOST_BLD:?The HOST_BLD environment variable is missing from your /home/alike/.env file}
            HOST_IP: ${HOST_IP:?The HOST_IP environment variable is missing from your /home/alike/.env file}
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
networks:
    alike-net:
        driver: bridge
