version: "3.7"
volumes:
    cache-dbs:
    instaboot:

services:
    alike:
        container_name: alike
        image: quadricsoftware/alike-v7:LTR
        stop_grace_period: 60s
        privileged: true
        init: true
        restart: always
        entrypoint: /a3init
        ports:
            - "80:80"
            - "443:443"
            - "445:445"
            - "222:22"
            - "111:111"
            - "2049:2049"
            - "2811:2811"
        tty: true
        volumes:
            - "/mnt/ads:/mnt/ads"
            - "/mnt/ods:/mnt/ods1"
            - "instaboot:/mnt/instaboot"
            - "./logs:/home/alike/logs"
            - "./certs:/home/alike/certs"
            - "./configs:/home/alike/configs"
            - "cache-dbs:/home/alike/Alike/remoteDBs"
        tmpfs:
            - /home/alike/Alike/temp:uid=1000,gid=33
            - /home/alike/Alike/DBs:uid=1000,gid=1000,exec
            - /run:uid=1000,gid=33
        networks:
            - alike-net
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        environment:
            - HOST_BLD=${HOST_BLD:?Please check your /home/alike/.env file}
            - HOST_IP=${HOST_IP:?Please check your /home/alike/.env file}
networks:
    alike-net:
        driver: bridge

